import {
  ProjectCreatedPayload as ContractsProjectCreatedPayloadSchema,
  ProjectMetaUpdatedPayload as ContractsProjectMetaUpdatedPayloadSchema,
  ProjectDeletedPayload as ContractsProjectDeletedPayloadSchema,
  ScheduledJobCreatedPayload as ContractsScheduledJobCreatedPayloadSchema,
  ScheduledJobUpdatedPayload as ContractsScheduledJobUpdatedPayloadSchema,
  ScheduledJobPausedPayload as ContractsScheduledJobPausedPayloadSchema,
  ScheduledJobResumedPayload as ContractsScheduledJobResumedPayloadSchema,
  ScheduledJobDeletedPayload as ContractsScheduledJobDeletedPayloadSchema,
  ScheduledJobRunStartedPayload as ContractsScheduledJobRunStartedPayloadSchema,
  ScheduledJobRunCompletedPayload as ContractsScheduledJobRunCompletedPayloadSchema,
  ThreadCreatedPayload as ContractsThreadCreatedPayloadSchema,
  ThreadArchivedPayload as ContractsThreadArchivedPayloadSchema,
  ThreadMetaUpdatedPayload as ContractsThreadMetaUpdatedPayloadSchema,
  ThreadRuntimeModeSetPayload as ContractsThreadRuntimeModeSetPayloadSchema,
  ThreadInteractionModeSetPayload as ContractsThreadInteractionModeSetPayloadSchema,
  ThreadDeletedPayload as ContractsThreadDeletedPayloadSchema,
  ThreadForkContextHydratedPayload as ContractsThreadForkContextHydratedPayloadSchema,
  ThreadUnarchivedPayload as ContractsThreadUnarchivedPayloadSchema,
  ThreadMessageSentPayload as ContractsThreadMessageSentPayloadSchema,
  ThreadProposedPlanUpsertedPayload as ContractsThreadProposedPlanUpsertedPayloadSchema,
  ThreadSessionSetPayload as ContractsThreadSessionSetPayloadSchema,
  ThreadTurnDiffCompletedPayload as ContractsThreadTurnDiffCompletedPayloadSchema,
  ThreadRevertedPayload as ContractsThreadRevertedPayloadSchema,
  ThreadActivityAppendedPayload as ContractsThreadActivityAppendedPayloadSchema,
  ThreadTurnStartRequestedPayload as ContractsThreadTurnStartRequestedPayloadSchema,
  ThreadTurnSteerRequestedPayload as ContractsThreadTurnSteerRequestedPayloadSchema,
  ThreadTurnInterruptRequestedPayload as ContractsThreadTurnInterruptRequestedPayloadSchema,
  ThreadFollowUpQueuedPayload as ContractsThreadFollowUpQueuedPayloadSchema,
  ThreadFollowUpUpdatedPayload as ContractsThreadFollowUpUpdatedPayloadSchema,
  ThreadFollowUpDeletedPayload as ContractsThreadFollowUpDeletedPayloadSchema,
  ThreadApprovalResponseRequestedPayload as ContractsThreadApprovalResponseRequestedPayloadSchema,
  ThreadCheckpointRevertRequestedPayload as ContractsThreadCheckpointRevertRequestedPayloadSchema,
  ThreadSessionStopRequestedPayload as ContractsThreadSessionStopRequestedPayloadSchema,
  ThreadYoloReviewCompletedPayload as ContractsThreadYoloReviewCompletedPayloadSchema,
  ThreadYoloStartedPayload as ContractsThreadYoloStartedPayloadSchema,
  ThreadYoloStoppedPayload as ContractsThreadYoloStoppedPayloadSchema,
} from "@t3tools/contracts";

// Server-internal alias surface, backed by contract schemas as the source of truth.
export const ProjectCreatedPayload = ContractsProjectCreatedPayloadSchema;
export const ProjectMetaUpdatedPayload = ContractsProjectMetaUpdatedPayloadSchema;
export const ProjectDeletedPayload = ContractsProjectDeletedPayloadSchema;
export const ScheduledJobCreatedPayload = ContractsScheduledJobCreatedPayloadSchema;
export const ScheduledJobUpdatedPayload = ContractsScheduledJobUpdatedPayloadSchema;
export const ScheduledJobPausedPayload = ContractsScheduledJobPausedPayloadSchema;
export const ScheduledJobResumedPayload = ContractsScheduledJobResumedPayloadSchema;
export const ScheduledJobDeletedPayload = ContractsScheduledJobDeletedPayloadSchema;
export const ScheduledJobRunStartedPayload = ContractsScheduledJobRunStartedPayloadSchema;
export const ScheduledJobRunCompletedPayload = ContractsScheduledJobRunCompletedPayloadSchema;

export const ThreadCreatedPayload = ContractsThreadCreatedPayloadSchema;
export const ThreadArchivedPayload = ContractsThreadArchivedPayloadSchema;
export const ThreadMetaUpdatedPayload = ContractsThreadMetaUpdatedPayloadSchema;
export const ThreadRuntimeModeSetPayload = ContractsThreadRuntimeModeSetPayloadSchema;
export const ThreadInteractionModeSetPayload = ContractsThreadInteractionModeSetPayloadSchema;
export const ThreadDeletedPayload = ContractsThreadDeletedPayloadSchema;
export const ThreadForkContextHydratedPayload = ContractsThreadForkContextHydratedPayloadSchema;
export const ThreadUnarchivedPayload = ContractsThreadUnarchivedPayloadSchema;

export const MessageSentPayloadSchema = ContractsThreadMessageSentPayloadSchema;
export const ThreadProposedPlanUpsertedPayload = ContractsThreadProposedPlanUpsertedPayloadSchema;
export const ThreadSessionSetPayload = ContractsThreadSessionSetPayloadSchema;
export const ThreadTurnDiffCompletedPayload = ContractsThreadTurnDiffCompletedPayloadSchema;
export const ThreadRevertedPayload = ContractsThreadRevertedPayloadSchema;
export const ThreadActivityAppendedPayload = ContractsThreadActivityAppendedPayloadSchema;
export const ThreadYoloStartedPayload = ContractsThreadYoloStartedPayloadSchema;
export const ThreadYoloStoppedPayload = ContractsThreadYoloStoppedPayloadSchema;
export const ThreadYoloReviewCompletedPayload = ContractsThreadYoloReviewCompletedPayloadSchema;

export const ThreadTurnStartRequestedPayload = ContractsThreadTurnStartRequestedPayloadSchema;
export const ThreadTurnSteerRequestedPayload = ContractsThreadTurnSteerRequestedPayloadSchema;
export const ThreadTurnInterruptRequestedPayload =
  ContractsThreadTurnInterruptRequestedPayloadSchema;
export const ThreadFollowUpQueuedPayload = ContractsThreadFollowUpQueuedPayloadSchema;
export const ThreadFollowUpUpdatedPayload = ContractsThreadFollowUpUpdatedPayloadSchema;
export const ThreadFollowUpDeletedPayload = ContractsThreadFollowUpDeletedPayloadSchema;
export const ThreadApprovalResponseRequestedPayload =
  ContractsThreadApprovalResponseRequestedPayloadSchema;
export const ThreadCheckpointRevertRequestedPayload =
  ContractsThreadCheckpointRevertRequestedPayloadSchema;
export const ThreadSessionStopRequestedPayload = ContractsThreadSessionStopRequestedPayloadSchema;
